### ISSUE TITLE
Avoid failures on unknown fields for Camel K resources

### ISSUE THREAD

**Issue by nicolaferraro** [citrusframework/yaks#264] opened 2021-03-12 09:56 UTC
I think YAKS should just ignore unknown fields added to status. E.g. it fails when finding the `firstTruthyTime` field in a condition (it should be a new field):

```
test-knative-broker-c15jhht3jdhs9cmf7m1g-8274n test Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "firstTruthyTime" (class org.citrusframework.yaks.camelk.model.IntegrationStatus$Condition), not marked as ignorable (6 known properties: "status", "reason", "message", "lastTransitionTime", "type", "lastUpdateTime"])
```

Note that a Camel K extension is going to be added to the fabric8-client (which I hope will be lenient): https://github.com/fabric8io/kubernetes-client/issues/2854

Using Camel K from master branch.

Test is the following:
```
Feature: Camel K can run latest released Knative CamelSource

  Background:
    Given Disable auto removal of Camel-K resources
    Given Disable auto removal of Kubernetes resources
    Given Camel-K resource polling configuration
      | maxAttempts          | 60   |
      | delayBetweenAttempts | 3000 |

  Scenario: Integration sends messages to the broker
    Given create Camel-K integration sender.groovy
    """
    from('timer:tick?period=1000')
      .setBody().constant('event-1')
      .to('knative:event/evt1')

    from('timer:tick?period=1000')
      .setBody().constant('event-2')
      .to('knative:event/evt2')

    from('timer:tick?period=1000')
      .setBody().constant('event-all')
      .to('knative:event')
    """
    Then Camel-K integration sender should be running


  Scenario: Integration receives the correct messages from the broker
    Given create Camel-K integration receiver.groovy
    """
    from('knative:event/evt1')
      .log('From evt1: $simple{body}')

    from('knative:event/evt2')
      .log('From evt2: $simple{body}')

    from('knative:event')
      .log('From all: $simple{body}')
    """
    Then Camel-K integration receiver should print From evt1: event-1
    And Camel-K integration receiver should print From evt2: event-2
    And Camel-K integration receiver should print From all: event-1
    And Camel-K integration receiver should print From all: event-2
    And Camel-K integration receiver should print From all: event-all
    And Camel-K integration receiver should not print From evt1: event-2
    And Camel-K integration receiver should not print From evt1: event-all
    And Camel-K integration receiver should not print From evt2: event-1
    And Camel-K integration receiver should not print From evt2: event-all
    And delete Camel-K integration sender
    And delete Camel-K integration receiver

```

**Comment by christophd** [comment] 2021-03-17 12:51
I think the marshal/unmarshal already ignores unused fields for the Kamelet spec. Let's do the same for the status, too.

**Comment by christophd** [comment] 2021-03-23 20:21
@nicolaferraro I could not reproduce this issue with yaks v0.3.0. I see that the e2e tests use yaks v0.1.0 (https://github.com/apache/camel-k/blob/master/.github/workflows/knative.yml#L194) could you please update and try with newer version

**Comment by nicolaferraro** [comment] 2021-03-24 09:29
I think I was trying it locally with 0.3.0. Let me recheck again.

**Comment by christophd** [comment] 2021-03-31 09:50
@nicolaferraro closing this one. please reopen if it is still an issue

**Closed by christophd** 2021-03-31 09:50 UTC
Labels: bug, invalid
